# Prek configuration for Java project
repos:
  - repo: local
    hooks:
      - id: gradle-spotless-apply
        name: Gradle Spotless (format)
        entry: ./gradlew
        language: system
        args: [ "spotlessApply" ]
        pass_filenames: false

      - id: checkstyle
        name: Checkstyle
        entry: ./gradlew
        language: system
        args: [ "checkstyleAll", "--quiet" ]
        pass_filenames: false

# Source - https://stackoverflow.com/a/66411313
# Posted by anthony sottile
# Retrieved 2026-03-18, License - CC BY-SA 4.0

  - repo: https://github.com/jorisroovers/gitlint
    rev: '4d9119760056492eabc201bfad5de2f9e660b85f'
    hooks:
    -   id: gitlint


  # Ministry of Justice DevSecOps hooks for secret detection
  # Not supporting custom api tokens of PDA service
  - repo: https://github.com/ministryofjustice/devsecops-hooks
    rev: v1.4.0
    hooks:
      - id: baseline
        # Exclude directories that are not part of the codebase
        exclude: |
          (?x)^(
            build/|
            .gradle/|
            .idea/|
            .git/|
          )