# Development Environment Values
appName: laa-record-controlled-work-api
namespace: laa-record-controlled-work-api-uat
serviceAccountName: rcw-api-github-action-service-account
environmentName: dev
replicaCount: 1
minReplicaCount: 1


image:
  repository: nginx
  pullPolicy: Always
  tag: "@sha256:1881968aff6f7cdcc4b888c00a11f4ce241ad7ec957e0cb4a9e19e93a3ff87ea"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  maxReplicaCount: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80  

ingress:
  green:
    className: beta
    hostname: "laa-record-controlled-work-api-uat.cloud-platform.service.justice.gov.uk"
    pathType: Prefix
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/hostname: "laa-record-controlled-work-api.beta.cloud-platform.service.justice.gov.uk"
      external-dns.alpha.kubernetes.io/aws-weight: "100"
      external-dns.alpha.kubernetes.io/set-identifier: "laa-record-controlled-work-uat-green"


podSecurityContext:
  runAsUser: 10001

securityContext:
  runAsUser: 10001

podAnnotations:
  environment: development

podLabels:
  environment: development


tolerations:
  - key: "monitoring-node"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  - key: "containment-node"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

# Development-specific configuration
configMap:
  enabled: true
  data:
    LOG_LEVEL: debug
    DEBUG_MODE: "true"
    ENVIRONMENT: development

# secrets:
#   enabled: true
#   # -- Secret name (if not set, will use app name)
#   name: ""
#   # -- Secret data key-value pairs (base64 encoded by values)
#   data: {}
#   # -- Mount Secret as volume
#   mountPath: ""
#   # -- Secret mount subPath
#   subPath: ""

# containerEnvironment:
#   enabled: true
#   variables:
#     APP_ENV: dev
#     LOG_LEVEL: debug

  # TODO datastore added this
# startupProbe:
#   httpGet:
#     path: /actuator/health
#     port: http
#   failureThreshold: 30
#   periodSeconds: 10

livenessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 60

readinessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 60

security:
  podSecurityStandard: baseline
  networkIsolation: false

certificate:
  enabled: false

service:
  port: 80

