name: Snyk OAuth Authentication
description: Fetches a Snyk OAuth Token

runs:
  using: composite
  steps:
    - name: Fetch Snyk OAuth Token
      shell: bash
      run: |
        TOKEN=$(curl -s -X POST "https://api.snyk.io/oauth2/token" \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "grant_type=client_credentials" \
          -d "client_id=$SNYK_CLIENT_ID" \
          -d "client_secret=$SNYK_CLIENT_SECRET" \
          | jq -r '.access_token')
          
        echo "SNYK_OAUTH_TOKEN=$TOKEN" >> $GITHUB_ENV

    
  
