openapi: "3.0.0"
info:
  version: 1.0.0
  title: Record Controlled Work API
paths:
  /api/v1/applications:
    get:
      tags:
        - applications
      summary: Get all applications
      operationId: getApplications
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          required: false
          schema:
            type: integer
            default: 25
        - name: officeId
          in: query
          required: false
          schema:
            type: string
        - name: status
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/ApplicationState"
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Applications"
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      tags:
        - applications
      summary: Create an application
      operationId: createApplication
      requestBody:
        description: create an application
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateApplicationRequestBody'
      responses:
        '201':
          description: 'Created'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateApplicationResponseBody'
          headers:
            Location:
              description: Canonical RCW application URL for the created application
              schema:
                type: string
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/v1/applications/{id}:
    get:
      tags:
        - applications
      summary: Get application by ID
      operationId: getApplication
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application"
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/v1/applications/{id}/evidence:
    put:
      tags:
        - applications
      summary: Update the evidence data for an application
      operationId: updateApplicationEvidence
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateEvidenceRequestBody"
      responses:
        '204':
          description: 'Application evidence data updated successfully'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/v1/applications/{id}/means:
    put:
      tags:
        - applications
      summary: Update the means data for an application
      operationId: updateApplicationMeans
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateMeansDataRequestBody"
      responses:
        '204':
          description: 'Application means data updated successfully'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/v1/applications/{id}/declaration:
    put:
      tags:
        - applications
      summary: Update the signed declaration for an application
      operationId: updateApplicationDeclaration
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateDeclarationRequestBody"
      responses:
        '204':
          description: 'Application declaration updated successfully'
        '400':
          description: 'Bad request'
        '401':
          description: 'Unauthorized'
        '403':
          description: 'Forbidden'
        '404':
          description: 'Not found'
        '409':
          description: 'Conflict'
        '500':
          description: 'Internal server error'

  /api/v1/applications/{id}/status:
    patch:
      tags:
        - applications
      summary: Update the application status
      operationId: updateApplicationStatus
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateApplicationStatusRequestBody"
      responses:
        '204':
          description: 'Application status updated successfully'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    ApplicationOverview:
      required:
        - id
        - name
        - applicationRefNumber
        - modifiedAt
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        applicationRefNumber:
          type: string
        modifiedAt:
          type: string
          format: date-time

    CreateApplicationRequestBody:
      type: object
      required:
        - legalAidBefore
        - providerOfficeCode
        - scopingQuestions
        - clientDetails
      properties:
        legalAidBefore:
          type: string
        legalAidLast6Months:
          type: boolean
        reasonForReapplication:
          type: string
        providerOfficeCode:
          type: string
        scopingQuestions:
          type: object
          additionalProperties: true
        clientDetails:
          $ref: "#/components/schemas/ClientDetails"

    CreateApplicationResponseBody:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          format: uuid

    Applications:
      type: array
      items:
        $ref: "#/components/schemas/ApplicationOverview"

    Application:
      type: object
      required:
        - id
        - individualLegalAidNumber
        - providerFirmCode
        - providerOfficeCode
        - createdAt
        - createdBy
        - modifiedAt
        - modifiedBy
        - clientDetails
        - applicationState
        - applicationType
      properties:
        id:
          type: string
          format: uuid
        applicationRefNumber:
          type: string
        individualLegalAidNumber:
          type: string
          format: uuid
        providerFirmCode:
          type: string
        providerOfficeCode:
          type: string
        meansAssessmentId:
          type: string
          format: uuid
        clientDetails:
          $ref: "#/components/schemas/ClientDetails"
        applicationState:
          $ref: "#/components/schemas/ApplicationState"
        declaration:
          $ref: "#/components/schemas/Declaration"
        evidence:
          $ref: "#/components/schemas/Evidence"
        eligibility:
          $ref: "#/components/schemas/Eligibility"
        reasonForReapplication:
          type: string
        meansAssessmentRequired:
          type: boolean
        typeOfNonMeans:
          type: boolean
        contribution:
          type: string
        scopingQuestions:
          type: object
        applicationType:
          type: string
        createdAt:
          type: string
          format: date-time
        createdBy:
          type: string
        modifiedAt:
          type: string
          format: date-time
        modifiedBy:
          type: string

    UpdateEvidenceRequestBody:
      type: object
      properties:
        evidenceExemptionCode:
          type: string
        evidenceExemptionReason:
          type: string
        incomeEvidenceChecklist:
          type: object
        expenditureCapitalEvidenceChecklist:
          type: object

    UpdateMeansDataRequestBody:
      type: object
      required:
        - data
        - result
      properties:
        data:
          type: object
        result:
          type: object

    UpdateApplicationStatusRequestBody:
      type: object
      required:
        - applicationState
        - eTag
      properties:
        applicationState:
          $ref: "#/components/schemas/ApplicationState"
        eTag:
          type: integer
          format: int64
          description: ETag value for optimistic concurrency control

    UpdateDeclarationRequestBody:
      type: object
      required:
        - declarationConfirmation
        - dateSigned
      properties:
        declarationConfirmation:
          type: boolean
        dateSigned:
          type: string
          format: date

    Eligibility:
      type: object
      properties:
        data:
          type: object
        result:
          type: object

    Declaration:
      type: object
      properties:
        id:
          type: string
          format: uuid
        declarationConfirmation:
          type: boolean
        dateSigned:
          type: string
          format: date
        createdAt:
          type: string
          format: date-time
        createdBy:
          type: string
        modifiedAt:
          type: string
          format: date-time
        modifiedBy:
          type: string

    Evidence:
      type: object
      properties:
        evidenceExemptionCode:
          type: string
        evidenceExemptionReason:
          type: string
        incomeEvidenceChecklist:
          type: object
        expenditureCapitalEvidenceChecklist:
          type: object

    ClientDetails:
      required:
        - firstName
        - lastName
        - dateOfBirth
        - hasFixedAddress
      type: object
      properties:
        id:
          type: string
          format: uuid
        firstName:
          type: string
        lastName:
          type: string
        dateOfBirth:
          type: string
          format: date
        niNumber:
          type: string
          minLength: 9
          maxLength: 9
          pattern: '[A-CEGHJ-NOPR-TW-Z]{2}[0-9]{6}[ABCDs]{1}'
        hasFixedAddress:
          type: boolean
        address:
          $ref: "#/components/schemas/Address"
        createdAt:
          type: string
          format: date-time
        modifiedAt:
          type: string
          format: date-time

    Address:
      required:
        - addressLine1
        - country
      type: object
      properties:
        id:
          type: string
          format: uuid
        addressLine1:
          type: string
        addressLine2:
          type: string
        addressLine3:
          type: string
        addressLine4:
          type: string
        townOrCity:
          type: string
        postCode:
          type: string
        county:
          type: string
        country:
          type: string
          maxLength: 2
        createdAt:
          type: string
          format: date-time
        modifiedAt:
          type: string
          format: date-time

    ApplicationState:
      type: string
      enum:
        - DRAFT
        - COMPLETED

    ProblemDetail:
      type: object
      required:
        - type
        - title
        - status
      properties:
        type:
          type: string
          format: uri
          description: URI reference identifying the problem type
          example: "about:blank"
        title:
          type: string
          description: Human-readable summary of the problem type
        status:
          type: integer
          format: int32
          description: HTTP status code
          example: 400
        detail:
          type: string
          description: Human-readable explanation specific to this occurrence
        instance:
          type: string
          format: uri
          description: URI reference identifying the specific occurrence
        reason:
          type: string
          description: Machine-readable code identifying the exact violation, e.g. APPLICATION_NOT_FOUND
          example: "APPLICATION_NOT_FOUND"

    BadRequestResponse:
      allOf:
        - $ref: "#/components/schemas/ProblemDetail"

    UnauthorizedResponse:
      allOf:
        - $ref: "#/components/schemas/ProblemDetail"

    ForbiddenResponse:
      allOf:
        - $ref: "#/components/schemas/ProblemDetail"

    NotFoundResponse:
      allOf:
        - $ref: "#/components/schemas/ProblemDetail"

    ConflictResponse:
      allOf:
        - $ref: "#/components/schemas/ProblemDetail"

    InternalServerErrorResponse:
      allOf:
        - $ref: "#/components/schemas/ProblemDetail"

  responses:
    BadRequest:
      description: 'Bad request'
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BadRequestResponse"
    Unauthorized:
      description: 'Unauthorized'
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/UnauthorizedResponse"
    Forbidden:
      description: 'Forbidden'
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ForbiddenResponse"
    NotFound:
      description: 'Not found'
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/NotFoundResponse"
    Conflict:
      description: 'Conflict'
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ConflictResponse"
    InternalServerError:
      description: 'Internal server error'
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/InternalServerErrorResponse"
