name: CICD

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-tests:
    name: Build and Test
    uses: ./.github/workflows/build-test.yml

  snyk-scan:
    name: Scan app and Docker image
    uses: ./.github/workflows/snyk-scan.yml

  notify-main-ci-failure:
    name: Notify Main CI Failure
    if: ${{ always() && github.ref == 'refs/heads/main' && contains(needs.*.result, 'failure') }}
    runs-on: ubuntu-latest
    environment: uat
    needs:
      - build-tests
      - snyk-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

#      - name: Notify Slack on CI failure
#        uses: ./.github/actions/notify-slack
#        with:
#          slack-bot-token: ${{ secrets.SLACK_ALERTS_BOT_TOKEN }}
#          slack-channel-id: ${{ vars.SLACK_ALERTS_CHANNEL_ID }}
#          slack-mention: ${{ vars.SLACK_ALERTS_MENTION }}
#          message: |
#            :red_circle: *CI failed for RCW `main` branch*
#
#            Jobs monitored:
#            `code-linting`, `code-security-audit`, `snyk`, `snyk-infra`, `mocha-unit-tests`, `playwright`, `build-image`
#
#            Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}

  deploy-uat:
    if: "!(github.event_name == 'pull_request' && github.actor == 'renovate[bot]')"
    uses: ministryofjustice/laa-reusable-github-actions/.github/workflows/cp-build-push-deploy.yml@main
    with:
      app_name: laa-record-controlled-work-api
      helm_chart: ./laa-generic-helm-chart
      environment: uat
      helm_release_name: laa-record-controlled-work-api
      helm_values_path: ./helm/values/uat.yml
      k8s_service_account: rcw-api-github-action-service-account
      dockerfile_requires_git: true
    secrets: inherit
    needs:
      - build-tests
      - snyk-scan