name: Deploy to staging

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  packages: write
  id-token: write
  security-events: write

jobs:
  build-push-deploy-staging:
    uses: ministryofjustice/laa-reusable-github-actions/.github/workflows/cp-build-push-deploy.yml@3b61534ec28baab6171267eb56187bb597e89d45 # main
    with:
      app_name: laa-record-controlled-work-api
      helm_chart: ./laa-generic-helm-chart
      environment: staging
      helm_release_name: laa-record-controlled-work-api
      helm_values_path: ./helm/values/staging.yml
      k8s_service_account: rcw-api-github-action-service-account
      dockerfile_requires_git: true
    secrets: inherit
