# Workflow: SCA ⚡️
# Description:
#   Scheduled and on-demand Security Composition Analysis run.
#   - Triggers: daily cron, PRs to main, workflow dispatch, branch protection rule.
#   - sca: Checks out repo, installs node, runs npm ci, executes ministryofjustice/sca action with dependency review configuration.

name: SCA ⚡️
run-name: Software Composition Analysis ⚡️

on:
  schedule:
    - cron: "0 6 * * *"

  pull_request:
    branches: ["main"]

  merge_group:

  workflow_dispatch:
  workflow_call:

jobs:
  skip:
    name: Skip SCA in merge queue
    runs-on: ubuntu-latest
    if: github.event_name == 'merge_group'
    steps:
      - name: Skip SCA in merge queue
        run: echo "Skipping SCA in merge queue"

  sca:
    name: Software Composition Analysis
    runs-on: ubuntu-latest
    if: github.event_name != 'merge_group'
    timeout-minutes: 30
    permissions:
      contents: write
      pull-requests: write
      issues: write
      security-events: write
      actions: read
    steps:
      - name: Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: "Set up Java 25 (Amazon corretto distro)"
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: corretto
          java-version: 25

      - name: "Set up Gradle (cache)"
        uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0

      - name: "Build classes without running tests"
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          ./gradlew clean assemble testClasses integrationTestClasses

      - name: ⚡️ SCA
        uses: ministryofjustice/devsecops-actions/sca@86248cec9a6bb1fd4dabc08a05178e0650d3af4f # Feature branch
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          # Container Scanning
          docker-images-file: ${{ github.workspace }}/docker-images.json

          # Dependency Management
          renovate: "false"

          # Custom Configurations
        #   codeql-config-file: ".github/config/codeql.yml"
          codeql-languages: "java"
          codeql-upload-findings: "always"


          