# Workflow: SCA ⚡️
# Description:
#   Scheduled and on-demand Security Composition Analysis run.
#   - Triggers: daily cron, PRs to main, workflow dispatch, branch protection rule.
#   - sca: Checks out repo, installs node, runs npm ci, executes ministryofjustice/sca action with dependency review configuration.

name: SCA ⚡️
run-name: Software Composition Analysis ⚡️

on:
  schedule:
    - cron: "0 6 * * *"

  pull_request:
    branches: ["main"]

  workflow_dispatch:
  workflow_call:

jobs:
  sca:
    name: Software Composition Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
      pull-requests: write
      issues: write
      security-events: write
      actions: read
    steps:
      - name: Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: "Set up Java 25 (Amazon corretto distro)"
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
        with:
          distribution: corretto
          java-version: 25

      - name: "Set up Gradle (cache)"
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

      - name: "Build classes without running tests"
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          ./gradlew clean assemble testClasses integrationTestClasses

      - name: ⚡️ SCA
        uses: ministryofjustice/devsecops-actions/sca@86248cec9a6bb1fd4dabc08a05178e0650d3af4f # Feature branch
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          # Container Scanning
          docker-images-file: ${{ github.workspace }}/docker-images.json

          # Dependency Management
          renovate: "false"

          # Custom Configurations
        #   codeql-config-file: ".github/config/codeql.yml"
          codeql-languages: "java"
          codeql-upload-findings: "always"